Django/code/03_REL/accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # /accounts/signup/
    path('signup/', views.signup, name='signup'),
    # /accounts/login/
    path('login/', views.login, name='login'),
    # /accounts/logout/
    path('logout/', views.logout, name='logout'),
]

Django/code/03_REL/rel/urls.py
# Master URL
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
]

Django/code/03_REL/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% include "base_nav.html" %}
  {% block content %}{% endblock content %}
</body>
</html>

Django/code/03_REL/templates/base_nav.html
<nav>
  <ul>
    <li>
      <a href="{% url "board:index" %}">Home</a>
    </li>
    {% comment %} 요청 보낸 사용자가 로그인하지 않았다면 {% endcomment %}
    {% if not request.user.is_authenticated %}
    <li>
      <a href="{% url "accounts:login" %}">Login</a>
    </li>
    <li>
      <a href="{% url "accounts:signup" %}">Signup</a>
    </li>
    {% comment %} 요청 보낸 사용자가 로그인 했다면 {% endcomment %}
    {% else %}
    <li>
      <a href="{% url "board:create" %}">New</a>
    </li>
    <li>
      <a href="{% url "accounts:logout" %}">{{ request.user }} - Logout</a>
    </li>
    {% endif %}
  </ul>
</nav>